## Definifion of variables

CC=
LD=
AR=
RM=

SRC_DIR=
LIB_DIR=
INCLUDE_DIR=

CFLAGS=
LDFLAGS=

LIB_FILES=

EXEC_NAME=

## Target liblinked-list-utils.a
## archive linked-list.o into library liblinked-list-utils.a
liblinked-list-utils.a:


## Target main.o
## compile main.c to produce an object file (main.o)
main.o:


## Target linked-list.o
## compile linked-list.c to produce an object file (linked-list.o)
linked-list.o:

## Target $(EXEC_NAME)
## link liblinked-list-utils.a and main.o to produce the executable (linked-list-exe)
$(EXEC_NAME):


## Target all: Useful? Where should be put in the makefile?
all: $(EXEC_NAME) liblinked-list-utils.a


## Target clean
clean:
	$(RM) *.o $(LIB_DIR)/*.a $(EXEC_NAME)
